image: node:latest

cache:
  paths:
    - node_modules/
    - app/bower_components


deploy_staging:
  stage: deploy
  environment: Staging
  only:
    - develop
  script:
    - npm install -g firebase-tools
    - npm install -g bower
    - npm install
    - firebase use --token $FIREBASE_TOKEN staging
    - firebase deploy -m "Pipeline $CI_PIPELINE_ID, build $CI_BUILD_ID" --non-interactive --token $FIREBASE_TOKEN

deploy_production:
  stage: deploy
  environment: Production
  only:
    - master
  script:
    - npm install -g firebase-tools
    - npm install -g bower
    - npm install
    - firebase use --token $FIREBASE_TOKEN production
    - firebase deploy -m "Pipeline $CI_PIPELINE_ID, build $CI_BUILD_ID" --non-interactive --token $FIREBASE_TOKEN
