version: 0.2

phases:
  install:
    commands:
      - echo Nothing to do in the install phase...
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
      - echo 'Environment:'
      - printenv
  build:
    commands:
      - echo Build started on `date`
      - echo Actually, this is a static site, so nothing to do in build phase...
      - date > public/date.txt
      - ls public
  post_build:
    commands:
      - echo Build completed on `date`
      - aws s3 cp ./ s3://$BUCKET_NAME/ --recursive --exclude "*" --include "*.html" --include "*.jpg" --include "*.ico" --include "*.png" --include "*.png" --include "*.jpg" --include "*.html" --include "*.png" --include "*.css" --include "*.min" --include "*.css" --include "*.svg" --include "*.woff2" --include "*.ttf" --include "*.woff" --include "*.eot"
#artifacts:
#  files:
#    - '**/*'
#  base-directory: public
